// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPjamBvqATGNm6Ex6xPe4aHkaDvzhHVOo',
    appId: '1:585433136052:web:d5219448e51fa77db190e1',
    messagingSenderId: '585433136052',
    projectId: 'fir-df691',
    authDomain: 'fir-df691.firebaseapp.com',
    databaseURL: 'https://fir-df691-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-df691.appspot.com',
    measurementId: 'G-XTFF2MKFHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxB-YVqaF8sePWXmbtcuVu_ms_UKO8ksw',
    appId: '1:585433136052:android:8d3a584af637a589b190e1',
    messagingSenderId: '585433136052',
    projectId: 'fir-df691',
    databaseURL: 'https://fir-df691-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-df691.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFpvdREix7LwYL0rcEehJ_KMK6099k1-k',
    appId: '1:585433136052:ios:424923047750f6a4b190e1',
    messagingSenderId: '585433136052',
    projectId: 'fir-df691',
    databaseURL: 'https://fir-df691-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-df691.appspot.com',
    iosClientId: '585433136052-332rim0f5gc7mhh6ij3rfoq5002q36a4.apps.googleusercontent.com',
    iosBundleId: 'com.uwna.groupsettlement2.RunnerTests',
  );
}
